Return to normal versions instead of branches

diff --git a/biomeroworker/Dockerfile b/biomeroworker/Dockerfile
--- a/biomeroworker/Dockerfile
+++ b/biomeroworker/Dockerfile
@@ -1,6 +1,6 @@
 FROM openmicroscopy/omero-server:5.6.18
 
-ARG BIOMERO_BRANCH=roi-output-options
+ARG BIOMERO_VERSION
 ARG BIOMERO_IMPORTER_VERSION
 
 USER root
@@ -41,11 +41,13 @@ ENV PATH="$PATH:/opt/bioformats2raw-0.12.0-rc1/bin"
 RUN yum -y install ack
 
 # force zarr < 3 for compatibility w/ omero-cli-zarr by installing biomero AFTER the importer
-# Track the ROI output feature branch. Refresh the layer when its head changes.
-ADD "https://api.github.com/repos/NL-BioImaging/biomero/commits/${BIOMERO_BRANCH}" /latest_commit_biomero
+# To track a branch instead of a release, uncomment the cache-bust line and use the git install:
+# ADD "https://api.github.com/repos/NL-BioImaging/biomero/commits/surf" /latest_commit_biomero
+# && $VIRTUAL_ENV/bin/python -m pip install "biomero[full] @ git+https://github.com/NL-BioImaging/biomero.git@surf"
+RUN test -n "$BIOMERO_VERSION" || (echo "BIOMERO_VERSION build arg is required" >&2; exit 1)
 RUN $VIRTUAL_ENV/bin/python -m pip install --upgrade pip \
     && $VIRTUAL_ENV/bin/python -m pip install --ignore-requires-python biomero-importer==${BIOMERO_IMPORTER_VERSION} \
-    && $VIRTUAL_ENV/bin/python -m pip install "biomero[full] @ git+https://github.com/NL-BioImaging/biomero.git@${BIOMERO_BRANCH}" \
+    && $VIRTUAL_ENV/bin/python -m pip install "biomero[full]==${BIOMERO_VERSION}" \
     && $VIRTUAL_ENV/bin/python -m pip install \
         scikit-image==0.25.2 omero-rois==0.4.1
 
diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -1,7 +1,6 @@
 FROM openmicroscopy/omero-server:5.6.18
 
-ARG BIOMERO_SCRIPTS_BRANCH=roi-output-options
-ARG LABEL2ROIS_BRANCH=roi-output-options
+ARG BIOMERO_VERSION
 ARG OMERO_ZARR_PIXEL_BUFFER_VERSION
 
 ENV OMERO_DIST=/opt/omero/server/OMERO.server
@@ -20,8 +19,8 @@ ADD server/00-restore-config.sh* /startup/
 # LDAP configuration - add with correct values
 # ADD server/01-ldap-config.omero /opt/omero/server/config/
 
-# Track the feature branches while the ROI output integration is tested.
-ADD "https://api.github.com/repos/NL-BioImaging/biomero-scripts/commits/${BIOMERO_SCRIPTS_BRANCH}" /latest_commit_biomero_scripts
+# Clone tagged release
+RUN test -n "$BIOMERO_VERSION" || (echo "BIOMERO_VERSION build arg is required" >&2; exit 1)
 RUN cd $OMERO_DIST/lib/scripts/ && \
     git clone --depth 1 --branch ${BIOMERO_SCRIPTS_BRANCH} --single-branch https://github.com/NL-BioImaging/biomero-scripts.git biomero && \
     rm -f biomero/admin/Example_Minimal_Slurm_Script.py && \
@@ -34,11 +33,11 @@ RUN rm -rf $OMERO_DIST/lib/scripts/biomero/tests
 RUN curl -o $OMERO_DIST/lib/scripts/omero/figure_scripts/Figure_To_Pdf.py \
     https://raw.githubusercontent.com/ome/omero-figure/refs/heads/master/omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py
 
-# Install the matching Labels2Rois feature branch. The API request invalidates
-# Docker's cache whenever the branch head changes.
-ADD "https://api.github.com/repos/Cellular-Imaging-Amsterdam-UMC/label2rois/commits/${LABEL2ROIS_BRANCH}" /latest_commit_label2rois
-RUN curl -fL -o $OMERO_DIST/lib/scripts/omero/util_scripts/Labels2Rois.py \
-    https://raw.githubusercontent.com/Cellular-Imaging-Amsterdam-UMC/label2rois/${LABEL2ROIS_BRANCH}/Labels2Rois.py
+# Install Labels2Rois script from main
+# Invalidate Docker's cache whenever the branch head changes.
+ADD "https://api.github.com/repos/Cellular-Imaging-Amsterdam-UMC/label2rois/commits/main" /latest_commit_label2rois
+RUN curl -o $OMERO_DIST/lib/scripts/omero/util_scripts/Labels2Rois.py \
+    https://raw.githubusercontent.com/Cellular-Imaging-Amsterdam-UMC/label2rois/main/Labels2Rois.py
 
 # Overwrite ICE configuration
 # COPY ice.config $OMERO_DIST/etc/templates/
diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -1,7 +1,7 @@
 FROM openmicroscopy/omero-web-standalone:5.31.1
 
 ARG OMERO_FORMS_VERSION
-ARG OMERO_BIOMERO_BRANCH=roi-output-options
+ARG OMERO_BIOMERO_VERSION
 
 USER root
 
@@ -39,9 +39,14 @@ ENV PATH="/usr/pgsql-12/bin:/usr/pgsql-14/bin:${PATH}"
 ### Install OMERO.biomero first ###
 ### BIOMERO.importer and BIOMERO.analyzer will be installed as a dependency of OMERO.biomero ###
 
-# Track the ROI output feature branch. Refresh the layer when its head changes.
-ADD "https://api.github.com/repos/NL-BioImaging/OMERO.biomero/commits/${OMERO_BIOMERO_BRANCH}" /latest_commit_omero_biomero
-RUN /opt/omero/web/venv3/bin/pip install "git+https://github.com/NL-BioImaging/OMERO.biomero.git@${OMERO_BIOMERO_BRANCH}" \
+# To track a branch instead of a release, uncomment the cache-bust line and use the git install:
+# ADD "https://api.github.com/repos/NL-BioImaging/OMERO.biomero/commits/surf" /latest_commit_omero_biomero
+# RUN /opt/omero/web/venv3/bin/pip install git+https://github.com/NL-BioImaging/OMERO.biomero.git@surf \
+#     && /opt/omero/web/venv3/bin/omero-biomero-setup
+
+# Install released OMERO.biomero from PyPI
+RUN test -n "$OMERO_BIOMERO_VERSION" || (echo "OMERO_BIOMERO_VERSION build arg is required" >&2; exit 1)
+RUN /opt/omero/web/venv3/bin/pip install omero-biomero==${OMERO_BIOMERO_VERSION} \
     && /opt/omero/web/venv3/bin/omero-biomero-setup
 
 ### Install OMERO.forms ###
