Surf (#21)
* Add more envvars-through and surf branches

* Update patches from SURF for web and envvar reading in processor

* Up

* Update config and agent debug skill

* Move to prerelease versions

diff --git a/biomeroworker/Dockerfile b/biomeroworker/Dockerfile
--- a/biomeroworker/Dockerfile
+++ b/biomeroworker/Dockerfile
@@ -41,10 +41,11 @@ ENV PATH="$PATH:/opt/bioformats2raw-0.12.0-rc1/bin"
 RUN yum -y install ack
 
 # force zarr < 3 for compatibility w/ omero-cli-zarr by installing biomero AFTER the importer
-# Cache bust when new commits are pushed to dev-bilayers
-# ADD "https://api.github.com/repos/NL-BioImaging/biomero/commits/dev-bilayers" /latest_commit_biomero
-RUN test -n "$BIOMERO_VERSION" || (echo "BIOMERO_VERSION build arg is required" >&2; exit 1) \
-    && $VIRTUAL_ENV/bin/python -m pip install --upgrade pip \
+# To track a branch instead of a release, uncomment the cache-bust line and use the git install:
+# ADD "https://api.github.com/repos/NL-BioImaging/biomero/commits/surf" /latest_commit_biomero
+# && $VIRTUAL_ENV/bin/python -m pip install "biomero[full] @ git+https://github.com/NL-BioImaging/biomero.git@surf"
+RUN test -n "$BIOMERO_VERSION" || (echo "BIOMERO_VERSION build arg is required" >&2; exit 1)
+RUN $VIRTUAL_ENV/bin/python -m pip install --upgrade pip \
     && $VIRTUAL_ENV/bin/python -m pip install --ignore-requires-python biomero-importer==${BIOMERO_IMPORTER_VERSION} \
     && $VIRTUAL_ENV/bin/python -m pip install "biomero[full]==${BIOMERO_VERSION}"
 
diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -42,13 +42,14 @@ COPY biomeroworker/slurm-config.ini /etc/slurm-config.ini
 ### Install OMERO.biomero first ###
 ### BIOMERO.importer and BIOMERO.analyzer will be installed as a dependency of OMERO.biomero ###
 
-# Install released OMERO.biomero from PyPI and run setup (commented out for dev branch):
-# RUN /opt/omero/web/venv3/bin/pip install omero-biomero==${OMERO_BIOMERO_VERSION} \
+# To track a branch instead of a release, uncomment the cache-bust line and use the git install:
+# ADD "https://api.github.com/repos/NL-BioImaging/OMERO.biomero/commits/surf" /latest_commit_omero_biomero
+# RUN /opt/omero/web/venv3/bin/pip install git+https://github.com/NL-BioImaging/OMERO.biomero.git@surf \
 #     && /opt/omero/web/venv3/bin/omero-biomero-setup
 
-# Install OMERO.biomero from PyPI
-RUN test -n "$OMERO_BIOMERO_VERSION" || (echo "OMERO_BIOMERO_VERSION build arg is required" >&2; exit 1) \
-    && /opt/omero/web/venv3/bin/pip install omero-biomero==${OMERO_BIOMERO_VERSION} \
+# Install released OMERO.biomero from PyPI
+RUN test -n "$OMERO_BIOMERO_VERSION" || (echo "OMERO_BIOMERO_VERSION build arg is required" >&2; exit 1)
+RUN /opt/omero/web/venv3/bin/pip install omero-biomero==${OMERO_BIOMERO_VERSION} \
     && /opt/omero/web/venv3/bin/omero-biomero-setup
 
 ### Install OMERO.forms ###
