Dev bilayers (#20)
* Added empty bilayers container

* Fix test container version

* Revert wrong change

* Update slurm-config.ini

* Update slurm-config.ini

* install branches for now

* Added new test container

* Update slurm-config.ini

* bump version

* Bump omero. Add docs on bilayers.

* Update docs on unsupported features from bilayers

* Update DOI to BIOMERO 2.0 in login page

* Update versions of deps

* Update license of biomero.importer to GPL-2

* Up biomero-importer

* Bump versions

* Add citation file

* Update versions

* Update versions

* Bump versions

* Fix double lines

---------

Co-authored-by: Joost de Folter <folterj@gmail.com>

diff --git a/biomeroworker/Dockerfile b/biomeroworker/Dockerfile
--- a/biomeroworker/Dockerfile
+++ b/biomeroworker/Dockerfile
@@ -1,4 +1,4 @@
-FROM openmicroscopy/omero-server:5.6.17
+FROM openmicroscopy/omero-server:5.6.18
 
 ARG BIOMERO_VERSION
 ARG BIOMERO_IMPORTER_VERSION
@@ -41,7 +41,10 @@ ENV PATH="$PATH:/opt/bioformats2raw-0.12.0-rc1/bin"
 RUN yum -y install ack
 
 # force zarr < 3 for compatibility w/ omero-cli-zarr by installing biomero AFTER the importer
-RUN $VIRTUAL_ENV/bin/python -m pip install --upgrade pip \
+# Cache bust when new commits are pushed to dev-bilayers
+# ADD "https://api.github.com/repos/NL-BioImaging/biomero/commits/dev-bilayers" /latest_commit_biomero
+RUN test -n "$BIOMERO_VERSION" || (echo "BIOMERO_VERSION build arg is required" >&2; exit 1) \
+    && $VIRTUAL_ENV/bin/python -m pip install --upgrade pip \
     && $VIRTUAL_ENV/bin/python -m pip install --ignore-requires-python biomero-importer==${BIOMERO_IMPORTER_VERSION} \
     && $VIRTUAL_ENV/bin/python -m pip install "biomero[full]==${BIOMERO_VERSION}"
 
diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -1,4 +1,4 @@
-FROM openmicroscopy/omero-server:5.6.17
+FROM openmicroscopy/omero-server:5.6.18
 
 ARG BIOMERO_VERSION
 ARG OMERO_ZARR_PIXEL_BUFFER_VERSION
@@ -19,8 +19,11 @@ ADD server/00-restore-config.sh* /startup/
 # LDAP configuration - add with correct values
 # ADD server/01-ldap-config.omero /opt/omero/server/config/
 
-# Clone specific release version
+# Clone branch
+# Cache bust when new commits are pushed to branch
+# ADD "https://api.github.com/repos/NL-BioImaging/biomero-scripts/commits/dev-bilayers" /latest_commit_biomero_scripts
 # We don't need the example scripts
+RUN test -n "$BIOMERO_VERSION" || (echo "BIOMERO_VERSION build arg is required" >&2; exit 1)
 RUN cd $OMERO_DIST/lib/scripts/ && \
     git clone --depth 1 --branch $BIOMERO_VERSION --single-branch https://github.com/NL-BioImaging/biomero-scripts.git biomero && \
     rm -f biomero/admin/Example_Minimal_Slurm_Script.py && \
diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -1,4 +1,4 @@
-FROM openmicroscopy/omero-web-standalone:5.31.0
+FROM openmicroscopy/omero-web-standalone:5.31.1
 
 ARG OMERO_FORMS_VERSION
 ARG OMERO_BIOMERO_VERSION
@@ -42,8 +42,13 @@ COPY biomeroworker/slurm-config.ini /etc/slurm-config.ini
 ### Install OMERO.biomero first ###
 ### BIOMERO.importer and BIOMERO.analyzer will be installed as a dependency of OMERO.biomero ###
 
-# Install released OMERO.biomero from PyPI
-RUN /opt/omero/web/venv3/bin/pip install omero-biomero==${OMERO_BIOMERO_VERSION} \
+# Install released OMERO.biomero from PyPI and run setup (commented out for dev branch):
+# RUN /opt/omero/web/venv3/bin/pip install omero-biomero==${OMERO_BIOMERO_VERSION} \
+#     && /opt/omero/web/venv3/bin/omero-biomero-setup
+
+# Install OMERO.biomero from PyPI
+RUN test -n "$OMERO_BIOMERO_VERSION" || (echo "OMERO_BIOMERO_VERSION build arg is required" >&2; exit 1) \
+    && /opt/omero/web/venv3/bin/pip install omero-biomero==${OMERO_BIOMERO_VERSION} \
     && /opt/omero/web/venv3/bin/omero-biomero-setup
 
 ### Install OMERO.forms ###
