Bump versions

diff --git a/biomeroworker/Dockerfile b/biomeroworker/Dockerfile
--- a/biomeroworker/Dockerfile
+++ b/biomeroworker/Dockerfile
@@ -43,9 +43,10 @@ RUN yum -y install ack
 # force zarr < 3 for compatibility w/ omero-cli-zarr by installing biomero AFTER the importer
 # Cache bust when new commits are pushed to dev-bilayers
 # ADD "https://api.github.com/repos/NL-BioImaging/biomero/commits/dev-bilayers" /latest_commit_biomero
-RUN $VIRTUAL_ENV/bin/python -m pip install --upgrade pip \
+RUN test -n "$BIOMERO_VERSION" || (echo "BIOMERO_VERSION build arg is required" >&2; exit 1) \
+    && $VIRTUAL_ENV/bin/python -m pip install --upgrade pip \
     && $VIRTUAL_ENV/bin/python -m pip install --ignore-requires-python biomero-importer==${BIOMERO_IMPORTER_VERSION} \
-    && $VIRTUAL_ENV/bin/python -m pip install "biomero[full]==2.7.0b2"
+    && $VIRTUAL_ENV/bin/python -m pip install "biomero[full]==${BIOMERO_VERSION}"
 
 ## Adjust processor code with BIOMERO Processor
 # This version forwards HTTP(S) PROXY environment variables to the subprocesses (scripts)
diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -23,8 +23,9 @@ ADD server/00-restore-config.sh* /startup/
 # Cache bust when new commits are pushed to branch
 # ADD "https://api.github.com/repos/NL-BioImaging/biomero-scripts/commits/dev-bilayers" /latest_commit_biomero_scripts
 # We don't need the example scripts
+RUN test -n "$BIOMERO_VERSION" || (echo "BIOMERO_VERSION build arg is required" >&2; exit 1)
 RUN cd $OMERO_DIST/lib/scripts/ && \
-    git clone --depth 1 --branch v2.7.0-beta.2 --single-branch https://github.com/NL-BioImaging/biomero-scripts.git biomero && \
+    git clone --depth 1 --branch $BIOMERO_VERSION --single-branch https://github.com/NL-BioImaging/biomero-scripts.git biomero && \
     rm -f biomero/admin/Example_Minimal_Slurm_Script.py && \
     rm -f biomero/__workflows/SLURM_CellPose_Segmentation.py
 
diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -47,7 +47,8 @@ COPY biomeroworker/slurm-config.ini /etc/slurm-config.ini
 #     && /opt/omero/web/venv3/bin/omero-biomero-setup
 
 # Install OMERO.biomero from PyPI
-RUN /opt/omero/web/venv3/bin/pip install omero-biomero==1.5.0b2 \
+RUN test -n "$OMERO_BIOMERO_VERSION" || (echo "OMERO_BIOMERO_VERSION build arg is required" >&2; exit 1) \
+    && /opt/omero/web/venv3/bin/pip install omero-biomero==${OMERO_BIOMERO_VERSION} \
     && /opt/omero/web/venv3/bin/omero-biomero-setup
 
 ### Install OMERO.forms ###
