Pin released shallow Image components

diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -4,7 +4,7 @@ ARG BIOMERO_SCRIPTS_VERSION
 ARG LABEL2ROIS_VERSION
 ARG OMERO_ZARR_PIXEL_BUFFER_VERSION
 
-ARG BIOMERO_SCRIPTS_BRANCH=fix/remote-shallower-preflight
+# ARG BIOMERO_SCRIPTS_BRANCH=master
 
 ENV OMERO_DIST=/opt/omero/server/OMERO.server
 ENV OMERO_ZARR_PIXEL_BUFFER_REPO=https://artifacts.glencoesoftware.com:443/artifactory/gs-omero-snapshots-local/com/glencoesoftware/omero/omero-zarr-pixel-buffer
@@ -24,18 +24,18 @@ ADD server/00-restore-config.sh* /startup/
 
 # Development option: uncomment the branch ARG and ADD/RUN block below, and
 # comment the release RUN block. The branch head invalidates the clone layer.
-ADD "https://api.github.com/repos/NL-BioImaging/biomero-scripts/commits/${BIOMERO_SCRIPTS_BRANCH}" /latest_commit_biomero_scripts
-RUN cd $OMERO_DIST/lib/scripts/ && \
-    git clone --depth 1 --branch ${BIOMERO_SCRIPTS_BRANCH} --single-branch https://github.com/NL-BioImaging/biomero-scripts.git biomero && \
-    rm -f biomero/admin/Example_Minimal_Slurm_Script.py && \
-    rm -f biomero/__workflows/SLURM_CellPose_Segmentation.py
-
-# Release option: install the tag selected by BIOMERO_SCRIPTS_VERSION.
-# RUN test -n "$BIOMERO_SCRIPTS_VERSION" || (echo "BIOMERO_SCRIPTS_VERSION build arg is required" >&2; exit 1)
+# ADD "https://api.github.com/repos/NL-BioImaging/biomero-scripts/commits/${BIOMERO_SCRIPTS_BRANCH}" /latest_commit_biomero_scripts
 # RUN cd $OMERO_DIST/lib/scripts/ && \
-#     git clone --depth 1 --branch ${BIOMERO_SCRIPTS_VERSION} --single-branch https://github.com/NL-BioImaging/biomero-scripts.git biomero && \
+#     git clone --depth 1 --branch ${BIOMERO_SCRIPTS_BRANCH} --single-branch https://github.com/NL-BioImaging/biomero-scripts.git biomero && \
 #     rm -f biomero/admin/Example_Minimal_Slurm_Script.py && \
 #     rm -f biomero/__workflows/SLURM_CellPose_Segmentation.py
+
+# Release option: install the tag selected by BIOMERO_SCRIPTS_VERSION.
+RUN test -n "$BIOMERO_SCRIPTS_VERSION" || (echo "BIOMERO_SCRIPTS_VERSION build arg is required" >&2; exit 1)
+RUN cd $OMERO_DIST/lib/scripts/ && \
+    git clone --depth 1 --branch ${BIOMERO_SCRIPTS_VERSION} --single-branch https://github.com/NL-BioImaging/biomero-scripts.git biomero && \
+    rm -f biomero/admin/Example_Minimal_Slurm_Script.py && \
+    rm -f biomero/__workflows/SLURM_CellPose_Segmentation.py
 
 # Do not expose repository tests as runnable OMERO scripts.
 RUN rm -rf $OMERO_DIST/lib/scripts/biomero/tests || true
