Finalize released component configuration

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -2,7 +2,6 @@ FROM openmicroscopy/omero-web-standalone:5.31.1
 
 ARG OMERO_FORMS_VERSION
 ARG OMERO_BIOMERO_VERSION
-ARG OMERO_BIOMERO_BRANCH=session-poller
 
 USER root
 
@@ -43,17 +42,18 @@ ENV PATH="/usr/pgsql-12/bin:/usr/pgsql-14/bin:${PATH}"
 # Development option: install an unpublished OMERO.biomero feature branch.
 # Querying its branch head invalidates this layer when new commits are pushed
 # to the same branch. Comment this ADD/RUN pair when using the release option.
-ADD "https://api.github.com/repos/NL-BioImaging/OMERO.biomero/commits/${OMERO_BIOMERO_BRANCH}" /latest_commit_omero_biomero
-RUN /opt/omero/web/venv3/bin/pip install \
-        "omero-biomero @ git+https://github.com/NL-BioImaging/OMERO.biomero.git@${OMERO_BIOMERO_BRANCH}" \
-    && /opt/omero/web/venv3/bin/omero-biomero-setup
+# ARG OMERO_BIOMERO_BRANCH=main
+# ADD "https://api.github.com/repos/NL-BioImaging/OMERO.biomero/commits/${OMERO_BIOMERO_BRANCH}" /latest_commit_omero_biomero
+# RUN /opt/omero/web/venv3/bin/pip install \
+#         "omero-biomero @ git+https://github.com/NL-BioImaging/OMERO.biomero.git@${OMERO_BIOMERO_BRANCH}" \
+#     && /opt/omero/web/venv3/bin/omero-biomero-setup
 
 # Release option: install the version selected in OMERO_BIOMERO_VERSION from
 # PyPI. Uncomment this pair and comment the development ADD/RUN pair above.
-# RUN test -n "$OMERO_BIOMERO_VERSION" || (echo "OMERO_BIOMERO_VERSION build arg is required" >&2; exit 1)
-# RUN /opt/omero/web/venv3/bin/pip install \
-#         "omero-biomero==${OMERO_BIOMERO_VERSION}" \
-#     && /opt/omero/web/venv3/bin/omero-biomero-setup
+RUN test -n "$OMERO_BIOMERO_VERSION" || (echo "OMERO_BIOMERO_VERSION build arg is required" >&2; exit 1)
+RUN /opt/omero/web/venv3/bin/pip install \
+        "omero-biomero==${OMERO_BIOMERO_VERSION}" \
+    && /opt/omero/web/venv3/bin/omero-biomero-setup
 
 ### Install OMERO.forms ###
 
