Install Zarr Viewer from PyPI

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -2,6 +2,7 @@ FROM openmicroscopy/omero-web-standalone:5.31.1
 
 ARG OMERO_FORMS_VERSION
 ARG OMERO_BIOMERO_VERSION
+ARG BIOMERO_ZARR_VIEWER_VERSION
 
 USER root
 
@@ -32,13 +33,9 @@ RUN /opt/omero/web/venv3/bin/pip install \
         omero-webtagging-tagsearch \
         whitenoise
 
-# The OME-Zarr viewer is vendored as a verified, platform-independent wheel
-# because it is not published on PyPI. See web/plugins/README.md.
-COPY web/plugins/biomero_zarr_viewer-0.1.10-py3-none-any.whl /tmp/
-RUN /opt/omero/web/venv3/bin/pip install --no-deps \
-        /tmp/biomero_zarr_viewer-0.1.10-py3-none-any.whl \
-    && rm -f /tmp/biomero_zarr_viewer-0.1.10-py3-none-any.whl
-
+# Install the released BIOMERO OME-Zarr Viewer from PyPI
+RUN test -n "$BIOMERO_ZARR_VIEWER_VERSION" || (echo "BIOMERO_ZARR_VIEWER_VERSION build arg is required" >&2; exit 1)
+RUN /opt/omero/web/venv3/bin/pip install biomero-zarr-viewer==${BIOMERO_ZARR_VIEWER_VERSION}
 
 # Update PATH manually based on known locations
 ENV PATH="/usr/pgsql-12/bin:/usr/pgsql-14/bin:${PATH}"
@@ -74,14 +71,12 @@ ADD web/local_omeroweb_edits/pretty_login/ome.login.css ./webgateway/static/webg
 
 # Configuration file and startup scripts
 ADD web/local_omeroweb_edits/01-default-webapps.omero /opt/omero/web/config/
-ADD web/local_omeroweb_edits/90-biomero-zarr-viewer.omero /opt/omero/web/config/
 ADD web/44-create_forms_user.py /startup/
 ADD web/45-fix-forms-config.sh /startup/
 RUN chmod +x /startup/45-fix-forms-config.sh && \
     chmod +x /startup/44-create_forms_user.py && \
     chown -R omero-web:omero-web /opt/omero/web/config && \
-    chmod 644 /opt/omero/web/config/01-default-webapps.omero \
-              /opt/omero/web/config/90-biomero-zarr-viewer.omero
+    chmod 644 /opt/omero/web/config/01-default-webapps.omero
 
 ### Better Buttons ###
 
